### ISSUE TITLE
Link inside the tooltip

### ISSUE THREAD

**Issue by Wolfpoint** [amazingSurge/jquery-asTooltip#4]
The content to display inside the tootip is decided via the value in the title attribute of the container.

But what if i want to give a link inside the tooltip. or if i want to give any image or any other html tags?

Is there any way to do so?

There are some plugins who provide the functionality to place html inside the tooltip.
https://www.screencast.com/t/dFQH1gg6R

**Comment by thecreation** [comment]
You can using content option for html tags.
```
$().asTooltip({
    html: '<a href="#”>link</a>'
});
```

**Comment by Wolfpoint** [comment]
Thanks for the answer but the above solution didn't work for me. But i figured out that using content instead of html worked fine. i.e

$().asTooltip({
    content: '<a href="#”>link</a>'
});
